from src.adaptation_maximizers.abstract_maximizer import AbstractMaximizer
from src.adaptation_maximizers.DIRECT1_maximizer import DIRECT1Maximizer
from src.adaptation_maximizers.scipydirect_wrapper import ScipyDirectMaximizer
from src.adaptation_maximizers.tgo_wrapper import TGOMaximizer
